apiVersion: v1
kind: Secret
metadata:
  name: prometheus-federation-scrape-config
  namespace: central-monitoring-system
stringData:
  prometheus-federation.yaml: |
    - job_name: "federation"
      metrics_path: "/federate"
      scheme: https
      metric_relabel_configs:
        - source_labels:
            - instance
          regex: prometheus\.([a-z0-9\-]+)\.[0-9\.]+\.sslip\.io:443
          target_label: cluster
        - source_labels:
            - exported_instance
          target_label: instance    
        - source_labels:
            - exported_job
          target_label: job    
        - action: labeldrop
          regex: exported_.*         
      params:
        "match[]": [ '{__name__=~".+"}' ]
      basic_auth:
        username: user
        password: password
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets: 
          - "prometheus.central.34.241.154.20.sslip.io:443"
          - "prometheus.fleet01.52.210.157.88.sslip.io:443"
          - "prometheus.fleet02.54.154.52.75.sslip.io:443"
          - "prometheus.fleet03.34.252.20.195.sslip.io:443"
